language: python
sudo: required
dist: xenial
python: "3.8"

cache:
  pip: true
  directories:
    - "$HOME/.cache/pypoetry"

install:
  - curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python
  - source $HOME/.poetry/env
  - pip install coveralls
  - poetry install -v

script:
  - poetry run pytest -m "not wip" tests/

after_success:
  - coveralls
