version: '3'
services:
  bot:
    image: katcr
  shortener:
    image: shortmagnet
    ports:
	- "8080:8080"
    links:
	- redis
  redis:
    image: redis

  volumes:
      - /var/run/katcr_bot/:/volume

volumes:
    db-data

